#!/usr/bin/env bash
set -euxf

VERSION=${1:-""}
PACKAGE="gnome-next-meeting-applet"

TMPD=$(mktemp -d /tmp/.${PACKAGE}.XXXXX)
exitit() { [[ -n ${TMPD} ]] && rm -rf ${TMPD} ;}
trap exitit EXIT

[[ -z ${VERSION} ]] && { echo "need new version"; exit 1; }

git clone --depth=1 ssh://aur@aur.archlinux.org/${PACKAGE} ${TMPD}

cd ${TMPD}
sed -E "s#(pkgver=).*#\1$VERSION#" -i PKGBUILD
updpkgsums
makepkg --printsrcinfo > .SRCINFO
git commit --sign -v -a -m "Update to ${VERSION}"
git push
