name: Pylint Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry==v1.6.1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: poetry
    - name: Install dependencies
      run: |
        poetry install -v
    - name: Test code
      run: |
        poetry run pytest -v
    - name: Lint code
      run: |
        poetry run pylint -r y gnma
