name: Pylint Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt install gobject-introspection pkg-config libcairo-dev libgirepository1.0-dev libdbus-1-dev
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: poetry
    - name: Install Poetry dependencies
      run: |
        make  requirements_tools
    - name: Test code
      run: |
        make test
    - name: Lint code
      run: |
        make lint
