name: Pylint Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry pylint
      run: |
        sudo apt install -y python3-dev gobject-introspection pkg-config libcairo-dev libgirepository1.0-dev libdbus-1-dev meson python-is-python3 python3-pip
        pip3 install -U poetry
        poetry install -v
    - name: Test code
      run: |
        poetry run pytest -v
    - name: Lint code
      run: |
        poetry run pylint -r y gnma
